# Generated by Django 3.2.4 on 2021-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='Faq',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Faqs'},
        ),
    ]
