# Generated by Django 3.2.4 on 2021-07-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_newslettersubscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscribe',
            options={'verbose_name': 'Newsletter Subscribe'},
        ),
    ]
