# Generated by Django 3.2.4 on 2021-08-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210808_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='intro',
        ),
    ]
