# Generated by Django 3.2.4 on 2021-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_body_blog_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro',
            field=models.TextField(default='Intro', max_length=500),
        ),
    ]
